# -*- coding: utf-8 -*-
"""fft_tlc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18HMCUUDi0EeYYrqtP2irfpXrWtp5Wlqk
"""

import matplotlib.pyplot as plt
from cmath import exp, pi
#acesso ao arquivo sinal.dat do drive
file = open('/content/drive/My Drive/sinal.dat', 'r')

#acesso ao arquivo sinal.dat de forma local
#file = open('sinal.dat', 'r')

#cria uma lista de resultados
results = list()
for line in file:

    #separa o indice dos numeros, que é o que interssa.
    columns = line.split() 
    # print(columns)  
    #transforma cada numero em float para que sejam realizados o calculos             
    if float(columns[1]):
        results.append(float( columns[1]))
# print(results)   
#for register in results:
#conta a partir do 1
results=results[:-1]
print(len(results))
#funcao fft
def fft(x):
    N = len(x)
    if N <= 1: return x
    even = fft(x[0::2]) 
    odd =  fft(x[1::2])
    T= [exp(-2j*pi*k/N)*odd[k] for k in range(N//2)]
    return [even[k] + T[k] for k in range(N//2)] + \
           [even[k] - T[k] for k in range(N//2)]
 
plt.figure(figsize=(20,10))
plt.subplot(121), plt.plot(results), plt.title("tempo")
plt.subplot(122), plt.plot(fft(results)), plt.title("frequência")
plt.ylabel('Amplitude')
plt.show()